# This workflow warns and then closes issues and PRs that have had no activity for a specified amount of time.
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/actions/stale
name: Mark stale issues and pull requests

on:
  workflow_dispatch:
    inputs:
      checkWhat:
        description: 'Check What?'
        required: true
        default: 'Both' 
        type: choice
        options:
        - Both
        - PR
        - Issue 
  schedule:
  - cron: '35 14 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/stale@v5.0.0
      if: ${{ github.event.inputs.checkWhat === 'Both' }}
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue has been stale.'
        stale-pr-message: 'This PR has been stale.'
    - name: Close Stale Issues Safely
      uses: DeMoorJasper/stale@v2.0.1
      if: ${{ github.event.inputs.checkWhat === 'Issue' }}
      with:
        # The number of days old an issue can be before marking it stale
        days-before-stale: 31
        # The number of days to wait to close an issue or pull request after it being marked stale
        days-before-close: 1
    - name: PR Automation
      uses: devjoes/pr-automation@v0.1.0
      if: ${{ github.event.inputs.checkWhat === 'PR' }}
      with:
        # Label of PRs to be automatically closed (or * for all PRs)
        autoCloseLabel: false
        # Label of PRs to be automatically merged (or * for all PRs)
        autoMergeLabel: false
        # Warn user their PR will be closed after it has been open for x duration (can be specified as 1s,2m,3h etc)
        warnClosingAfter: 31d
        # Auto close PRs x duration after author has been warned (can be specified as 1s,2m,3h etc)
        autoCloseAfterWarn: 1d
        # Label to apply to PRs that are closing soon
        closingSoonLabel: false
        # PRs where these branches are the base or head will be ignored.
        branchBlackList: main
